# Generated by Django 5.1 on 2026-04-23 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceipt',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry'),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customerreceipt'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry'),
        ),
        migrations.AddField(
            model_name='receiptallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='invoices',
            field=models.ManyToManyField(through='sales.ReceiptAllocation', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='cost_of_goods_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='revenue_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
    ]
