# Generated by Django 5.1 on 2026-04-23 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_pricelist_customer_customer_type_customer_price_list_and_more'),
        ('treasury', '0002_banktransaction_bankreconciliation_cashtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='credit', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesrepresentative'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], default='draft', max_length=20),
        ),
    ]
