# Generated by Django 5.1 on 2026-04-23 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0004_salesinvoice_cash_box_salesinvoice_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceipt',
            name='cheque_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك'), ('intermediary', 'شركة وسيطة (فوري/أمان)')], max_length=20),
        ),
        migrations.CreateModel(
            name='IntermediaryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
            ],
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='intermediary_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.intermediarycompany'),
        ),
    ]
