# Generated by Django 6.0.4 on 2026-04-24 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_journalline_account'),
        ('sales', '0006_salesinvoiceline_tax_type'),
        ('treasury', '0002_banktransaction_bankreconciliation_cashtransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='account',
            field=models.OneToOneField(blank=True, help_text='حساب ذمة المندوب — يُنشأ تلقائياً', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.account'),
        ),
        migrations.CreateModel(
            name='RepDailySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cash_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesrepresentative')),
                ('to_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rep_settlements_received', to='treasury.bankaccount')),
                ('to_cash_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rep_settlements_received', to='treasury.cashbox')),
            ],
        ),
        migrations.CreateModel(
            name='RepSettlementInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesinvoice')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='sales.repdailysettlement')),
            ],
            options={
                'unique_together': {('settlement', 'invoice')},
            },
        ),
    ]
