# Generated by Django 6.0.4 on 2026-04-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_item_unit_item_base_unit_and_more'),
        ('sales', '0009_quotation_quotationline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure'),
        ),
    ]
