# Generated by Django 6.0.4 on 2026-04-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesinvoiceline_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceipt',
            name='collected_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
