# Generated by Django 6.0.4 on 2026-04-25 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_journalline_account'),
        ('sales', '0011_customerreceipt_collected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcenter'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='تكلفة الوحدة وقت البيع', max_digits=18),
        ),
    ]
