# Generated by Django 6.0.4 on 2026-04-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesinvoice_cost_center_salesinvoiceline_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='تكلفة الوحدة وقت المرتجع', max_digits=18),
        ),
    ]
