# Generated by Django 6.0.4 on 2026-04-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fiscalyear_fy_dates_valid'),
        ('sales', '0013_salesreturn_discount_amount_salesreturnline_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype'),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype'),
        ),
    ]
