# Generated by Django 6.0.4 on 2026-04-26 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fiscalyear_fy_dates_valid'),
        ('sales', '0014_quotationline_tax_percent2_quotationline_tax_type2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_tax1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.taxtype', verbose_name='الضريبة الافتراضية 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_tax2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.taxtype', verbose_name='الضريبة الافتراضية 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_taxable',
            field=models.BooleanField(default=True, verbose_name='خاضع للضريبة'),
        ),
    ]
