# Generated by Django 6.0.4 on 2026-04-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_customer_default_tax1_customer_default_tax2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='sales_rep',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='tax_percent2',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='tax_type',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='tax_type2',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='total',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='quotation',
            name='end_date',
            field=models.DateField(default='2026-04-26', verbose_name='تاريخ الانتهاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='name',
            field=models.CharField(default='عرض جديد', max_length=200, verbose_name='اسم العرض'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='start_date',
            field=models.DateField(default='2026-04-26', verbose_name='تاريخ البدء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationline',
            name='extra_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة خصم إضافية %'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customersector', verbose_name='القطاع'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customersector', verbose_name='القطاع المستهدف'),
        ),
    ]
