# Generated by Django 6.0.4 on 2026-05-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_customersector_remove_quotation_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sales.customersector', verbose_name='القطاع المستهدف'),
            preserve_default=False,
        ),
    ]
