# Generated by Django 6.0.4 on 2026-05-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_payslipitem'),
        ('sales', '0017_alter_quotation_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to='hr.employee', verbose_name='الموظف المرتبط'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='name',
            field=models.CharField(help_text='سيتم جلبه تلقائياً من الموظف', max_length=200),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
