# Generated by Django 6.0.4 on 2026-05-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_salesrepresentative_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
