# Generated by Django 6.0.4 on 2026-05-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journalentry_posted_at_journalentry_posted_by_and_more'),
        ('inventory', '0012_loadingorder_journal_entry'),
        ('sales', '0020_salestarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesrepresentative', verbose_name='مندوب المبيعات'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taxtype'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customersector', verbose_name='القطاع المستهدف'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('invoiced', 'محول لفاتورة'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='draft', max_length=20),
        ),
    ]
