# Generated by Django 6.0.4 on 2026-05-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_salesinvoiceline_extra_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='extra_discount_percent',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceline',
            name='extra_discount_percent',
        ),
    ]
