# Generated by Django 6.0.4 on 2026-05-16 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_remove_quotationline_extra_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='customer',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='extra_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='نسبة خصم إضافي %'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة 1'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='tax_percent2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة 2'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, verbose_name='الإجمالي'),
        ),
    ]
