# Generated by Django 6.0.4 on 2026-05-16 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_account_updated_at_account_version_and_more'),
        ('inventory', '0014_remove_warehousetransfer_item_and_more'),
        ('sales', '0024_customer_created_at_customer_updated_at_and_more'),
        ('treasury', '0005_remove_bankreconciliation_is_reconciled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='حد الائتمان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='credit', max_length=10, verbose_name='نوع التعامل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms_days',
            field=models.IntegerField(default=30, verbose_name='فترة السداد (أيام)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.pricelist', verbose_name='قائمة الأسعار'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة المستلمة'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='cheque_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استحقاق الشيك'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الشيك'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='collected_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإيداع'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='date',
            field=models.DateField(verbose_name='تاريخ التحصيل'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='intermediary_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.intermediarycompany', verbose_name='الشركة الوسيطة'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='invoices',
            field=models.ManyToManyField(through='sales.ReceiptAllocation', to='sales.salesinvoice', verbose_name='الفواتير المسددة'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='is_collected',
            field=models.BooleanField(default=False, verbose_name='تم التحصيل الفعلي'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم السند'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك'), ('intermediary', 'شركة وسيطة (فوري/أمان)')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='المرجع'),
        ),
        migrations.AlterField(
            model_name='customersector',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='customersector',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم القطاع'),
        ),
        migrations.AlterField(
            model_name='intermediarycompany',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب الوسيط'),
        ),
        migrations.AlterField(
            model_name='intermediarycompany',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة عمولة التحصيل (%)'),
        ),
        migrations.AlterField(
            model_name='intermediarycompany',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='intermediarycompany',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='القائمة الافتراضية'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم القائمة'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='min_qty',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14, verbose_name='أقل كمية'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.pricelist', verbose_name='قائمة الأسعار'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة (للنقدي)'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateField(verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='due_date',
            field=models.DateField(verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='credit', max_length=10, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesrepresentative', verbose_name='المندوب'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الإجمالي النهائي'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='تكلفة الوحدة وقت البيع', max_digits=18, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='cost_of_goods_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account', verbose_name='حساب تكلفة المبيعات'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='revenue_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='حساب الإيرادات'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taxtype', verbose_name='نوع الضريبة 1'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype', verbose_name='نوع الضريبة 2'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='account',
            field=models.OneToOneField(blank=True, help_text='حساب ذمة المندوب — يُنشأ تلقائياً', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='حساب العهدة'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='cash_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='خزنة المندوب'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود المندوب'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة (%)'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='name',
            field=models.CharField(help_text='سيتم جلبه تلقائياً من الموظف', max_length=200, verbose_name='اسم المندوب'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesrepresentative', verbose_name='المشرف المباشر'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='territory',
            field=models.CharField(blank=True, max_length=200, verbose_name='المنطقة/النطاق'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='مخزن المندوب'),
        ),
    ]
