# Generated by Django 6.0.4 on 2026-05-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_customer_account_alter_customer_address_and_more'),
        ('treasury', '0008_alter_mobilewallet_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='repdailysettlement',
            name='to_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rep_settlements_received', to='treasury.mobilewallet'),
        ),
    ]
