# Generated by Django 6.0.4 on 2026-05-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_repdailysettlement_to_wallet'),
        ('treasury', '0008_alter_mobilewallet_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة (للنقدي)'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='credit', max_length=10, verbose_name='نوع السداد'),
        ),
    ]
