# Generated by Django 6.0.4 on 2026-05-24 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemnotification'),
        ('inventory', '0015_warehouse_is_returns'),
        ('sales', '0027_salesreturn_cash_box_salesreturn_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['code'], 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='customerreceipt',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'سند تحصيل', 'verbose_name_plural': 'سندات التحصيل'},
        ),
        migrations.AlterModelOptions(
            name='customersector',
            options={'ordering': ['name'], 'verbose_name': 'قطاع عميل', 'verbose_name_plural': 'قطاعات العملاء'},
        ),
        migrations.AlterModelOptions(
            name='intermediarycompany',
            options={'ordering': ['name'], 'verbose_name': 'شركة وسيطة', 'verbose_name_plural': 'الشركات الوسيطة'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['name'], 'verbose_name': 'قائمة أسعار', 'verbose_name_plural': 'قوائم الأسعار'},
        ),
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'verbose_name': 'سعر صنف', 'verbose_name_plural': 'أسعار الأصناف'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-start_date', '-id'], 'verbose_name': 'عرض سعر', 'verbose_name_plural': 'عروض الأسعار'},
        ),
        migrations.AlterModelOptions(
            name='quotationline',
            options={'verbose_name': 'صنف في عرض سعر', 'verbose_name_plural': 'أصناف عروض الأسعار'},
        ),
        migrations.AlterModelOptions(
            name='receiptallocation',
            options={'verbose_name': 'توزيع تحصيل', 'verbose_name_plural': 'توزيعات التحصيل'},
        ),
        migrations.AlterModelOptions(
            name='repdailysettlement',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'تسوية يومية', 'verbose_name_plural': 'التسويات اليومية'},
        ),
        migrations.AlterModelOptions(
            name='repsettlementinvoice',
            options={'verbose_name': 'فاتورة تسوية', 'verbose_name_plural': 'فواتير التسوية'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'فواتير المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceline',
            options={'verbose_name': 'صنف في فاتورة مبيعات', 'verbose_name_plural': 'أصناف فواتير المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='salesrepresentative',
            options={'ordering': ['name'], 'verbose_name': 'مندوب مبيعات', 'verbose_name_plural': 'مندوبي المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'مرتجع مبيعات', 'verbose_name_plural': 'مرتجعات المبيعات'},
        ),
        migrations.AlterModelOptions(
            name='salesreturnline',
            options={'verbose_name': 'صنف في مرتجع', 'verbose_name_plural': 'أصناف المرتجعات'},
        ),
        migrations.RemoveField(
            model_name='customerreceipt',
            name='is_collected',
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='cheque_status',
            field=models.CharField(choices=[('pending', 'قيد التحصيل'), ('collected', 'تم التحصيل'), ('bounced', 'شيك مرتجع'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الشيك'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ التحصيل'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك'), ('intermediary', 'شركة وسيطة (فوري/أمان)')], db_index=True, max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم العرض'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('invoiced', 'محول لفاتورة'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotation', verbose_name='العرض'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taxtype', verbose_name='نوع الضريبة'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='date',
            field=models.DateField(db_index=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم التسوية'),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesrepresentative', verbose_name='المندوب'),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='repsettlementinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='repsettlementinvoice',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='sales.repdailysettlement', verbose_name='التسوية'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='date',
            field=models.DateField(db_index=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم المرتجع'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.salesrepresentative', verbose_name='المندوب'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='cogs_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account', verbose_name='حساب تكلفة المبيعات'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='تكلفة الوحدة وقت المرتجع', max_digits=18, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='return_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.account', verbose_name='حساب المردودات'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='sales_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesreturn', verbose_name='المرتجع'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة 2'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taxtype', verbose_name='نوع الضريبة'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype', verbose_name='نوع الضريبة 2'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المخزن'),
        ),
    ]
