# Generated by Django 5.1 on 2026-06-01 10:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_customerreceipt_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='حد الائتمان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_terms_days',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='فترة السداد (أيام)'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='intermediarycompany',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة عمولة التحصيل (%)'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='min_qty',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='أقل كمية'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الضريبة'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='receiptallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='cash_delivered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='repdailysettlement',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي النهائي'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='تكلفة الوحدة وقت البيع', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الخصم %'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='extra_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة خصم إضافي %'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة ضريبة 1'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='tax_percent2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة ضريبة 2'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة العمولة (%)'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='تكلفة الوحدة وقت المرتجع', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الضريبة'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الضريبة 2'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الوحدة'),
        ),
    ]
