# Generated by Django 5.1 on 2026-04-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('vat', 'ضريبة القيمة المضافة'), ('wht', 'ضريبة الخصم والتحصيل'), ('stamp', 'ضريبة دمغة'), ('other', 'أخرى')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='النسبة المئوية (مثال: 14.00)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(help_text='الحساب المحاسبي المرتبط', on_delete=django.db.models.deletion.PROTECT, to='core.account')),
            ],
        ),
    ]
