# Generated by Django 5.1 on 2026-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='account',
            name='initial_balance_type',
            field=models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], default='debit', max_length=10),
        ),
    ]
