# Generated by Django 5.1 on 2026-04-23 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_initial_balance_account_initial_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='core.account'),
        ),
    ]
