# Generated by Django 6.0.4 on 2026-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fiscalyear_fy_dates_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtype',
            name='category',
            field=models.CharField(choices=[('vat', 'ضريبة القيمة المضافة'), ('table', 'ضريبة الجدول'), ('wht', 'ضريبة الخصم والتحصيل (تحت حساب الضريبة)'), ('stamp', 'ضريبة الدمغة'), ('salary', 'ضريبة كسب العمل'), ('income', 'ضريبة الدخل (شركات/أفراد)'), ('estate', 'ضريبة التصرفات العقارية'), ('customs', 'ضرائب جمركية'), ('insurance', 'تأمينات اجتماعية'), ('other', 'أخرى')], max_length=20),
        ),
    ]
