# Generated by Django 6.0.4 on 2026-05-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_taxtype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['code'], 'verbose_name': 'مركز تكلفة', 'verbose_name_plural': 'مراكز التكلفة'},
        ),
        migrations.AddField(
            model_name='costcenter',
            name='center_type',
            field=models.CharField(choices=[('production', 'إنتاج / تشغيل'), ('service', 'خدمات آلات ومعدات'), ('marketing', 'خدمات تسويقية'), ('admin', 'خدمات إدارية ومالية'), ('capital', 'عمليات رأسمالية'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المركز'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف / الملاحظات'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='is_leaf',
            field=models.BooleanField(default=True, verbose_name='مركز طرفي (يقبل قيوداً)'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.costcenter', verbose_name='المركز الرئيسي'),
        ),
    ]
