# Generated by Django 6.0.4 on 2026-05-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journalentry_posted_at_journalentry_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxtype',
            options={'verbose_name': 'نوع الضريبة', 'verbose_name_plural': 'أنواع الضرائب'},
        ),
        migrations.AddField(
            model_name='taxtype',
            name='appear_in_invoices',
            field=models.BooleanField(default=True, verbose_name='تظهر في فواتير البيع والشراء'),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='appear_in_payroll',
            field=models.BooleanField(default=False, verbose_name='تظهر في مسيرات الرواتب'),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب المحاسبي المرتبط'),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='category',
            field=models.CharField(choices=[('vat', 'ضريبة القيمة المضافة'), ('table', 'ضريبة الجدول'), ('wht', 'ضريبة الخصم والتحصيل (تحت حساب الضريبة)'), ('stamp', 'ضريبة الدمغة'), ('salary', 'ضريبة كسب العمل'), ('estate', 'ضريبة التصرفات العقارية'), ('customs', 'ضرائب جمركية'), ('insurance', 'تأمينات اجتماعية'), ('other', 'أخرى')], default='vat', max_length=20, verbose_name='تصنيف الضريبة'),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الضريبة'),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='النسبة الافتراضية (%)'),
        ),
    ]
