# Generated by Django 6.0.4 on 2026-05-27 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalline',
            options={'ordering': ['entry', 'id']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_entries', to='core.journalentry'),
        ),
    ]
