# Generated by Django 5.1 on 2026-06-01 09:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_journalline_options_alter_auditlog_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='النسبة الافتراضية (%)'),
        ),
    ]
