# Generated by Django 5.1 on 2026-04-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('movement_type', models.CharField(choices=[('purchase_in', 'استلام مشتريات'), ('sales_out', 'صرف مبيعات'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('adj_in', 'تسوية زيادة'), ('adj_out', 'تسوية نقص'), ('opening', 'رصيد افتتاحي')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('running_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('running_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('item', 'warehouse')},
            },
        ),
    ]
