# Generated by Django 5.1 on 2026-04-23 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehousetransfer'),
        ('sales', '0004_salesinvoice_cash_box_salesinvoice_payment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', 'استلام مشتريات'), ('sales_out', 'صرف مبيعات'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('adj_in', 'تسوية زيادة'), ('adj_out', 'تسوية نقص'), ('opening', 'رصيد افتتاحي'), ('loading_in', 'تحميل وارد (للمندوب)'), ('loading_out', 'تحميل صادر (من المخزن)')], max_length=20),
        ),
        migrations.CreateModel(
            name='LoadingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'في انتظار الاعتماد'), ('approved', 'معتمد'), ('issued', 'تم الصرف'), ('cancelled', 'ملغي')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loadings', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_orders_out', to='inventory.warehouse')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_loadings', to=settings.AUTH_USER_MODEL)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesrepresentative')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_orders_in', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='LoadingOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('approved_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('issued_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('loading_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.loadingorder')),
            ],
        ),
    ]
