# Generated by Django 6.0.4 on 2026-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_movement_type_loadingorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', 'استلام مشتريات'), ('sales_out', 'صرف مبيعات'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('adj_in', 'تسوية زيادة'), ('adj_out', 'تسوية نقص'), ('opening', 'رصيد افتتاحي'), ('loading_in', 'تحميل وارد (للمندوب)'), ('loading_out', 'تحميل صادر (من المخزن)'), ('sale_return', 'مرتجع مبيعات')], max_length=20),
        ),
    ]
