# Generated by Django 6.0.4 on 2026-04-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_journalline_account'),
        ('inventory', '0006_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='core.account'),
        ),
    ]
