# Generated by Django 6.0.4 on 2026-04-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockvoucher_stockvoucherline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items_as_base', to='inventory.unitofmeasure', verbose_name='الوحدة الأساسية (أصغر وحدة)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='كم وحدة أساسية توجد في وحدة المبيعات؟', max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_as_purchase', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_as_sales', to='inventory.unitofmeasure'),
        ),
    ]
