# Generated by Django 6.0.4 on 2026-04-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_item_unit_item_base_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='costing_method',
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='كم وحدة أساسية توجد في وحدة المشتريات؟', max_digits=10),
        ),
    ]
