# Generated by Django 6.0.4 on 2026-05-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_costcenter_options_costcenter_center_type_and_more'),
        ('inventory', '0010_remove_item_costing_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account', verbose_name='حساب المخزون (أستاذ عام)'),
        ),
    ]
