# Generated by Django 6.0.4 on 2026-05-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_costcenter_options_costcenter_center_type_and_more'),
        ('inventory', '0011_warehouse_gl_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingorder',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
    ]
