# Generated by Django 6.0.4 on 2026-05-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_loadingorder_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='السعر الافتراضي'),
        ),
    ]
