# Generated by Django 6.0.4 on 2026-05-16 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_account_updated_at_account_version_and_more'),
        ('inventory', '0013_item_standard_price'),
        ('sales', '0024_customer_created_at_customer_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousetransfer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='warehousetransfer',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemcategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود الصنف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cogs_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cogs_items', to='core.account', verbose_name='حساب التكلفة (مصروف)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='كم وحدة أساسية توجد في وحدة المبيعات؟', max_digits=10, verbose_name='معامل تحويل البيع'),
        ),
        migrations.AlterField(
            model_name='item',
            name='inventory_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='core.account', verbose_name='حساب المخزون (أصول)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='حد الطلب'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300, verbose_name='اسم الصنف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='كم وحدة أساسية توجد في وحدة المشتريات؟', max_digits=10, verbose_name='معامل تحويل الشراء'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_as_purchase', to='inventory.unitofmeasure', verbose_name='وحدة المشتريات'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='core.account', verbose_name='حساب المبيعات (إيراد)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_as_sales', to='inventory.unitofmeasure', verbose_name='وحدة المبيعات'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود التصنيف'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemcategory', verbose_name='التصنيف الأب'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loadings', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='date',
            field=models.DateField(verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_orders_out', to='inventory.warehouse', verbose_name='من مخزن (الرئيسي)'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف الفعلي'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_loadings', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesrepresentative', verbose_name='مندوب المبيعات'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'في انتظار الاعتماد'), ('approved', 'معتمد'), ('issued', 'تم الصرف'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='loadingorder',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_orders_in', to='inventory.warehouse', verbose_name='إلى مخزن (المندوب)'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإذن'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الإذن'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='offset_account',
            field=models.ForeignKey(blank=True, help_text='الحساب المقابل (مثل: حساب التلفيات، مصروفات العينات، إلخ)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب المقابل'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='voucher_type',
            field=models.CharField(choices=[('receipt', 'إذن إضافة'), ('issue', 'إذن صرف')], max_length=10, verbose_name='نوع الإذن'),
        ),
        migrations.AlterField(
            model_name='stockvoucher',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='stockvoucherline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سيتم حسابه تلقائياً عند الترحيل إذا كان إذن صرف', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='كود الوحدة'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الوحدة'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود المخزن'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.TextField(blank=True, verbose_name='العنوان/الموقع'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المخزن'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='date',
            field=models.DateField(verbose_name='تاريخ التحويل'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse', verbose_name='من مخزن'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّب'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse', verbose_name='إلى مخزن'),
        ),
        migrations.CreateModel(
            name='WarehouseTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='تكلفة الوحدة')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.warehousetransfer', verbose_name='طلب التحويل')),
            ],
        ),
    ]
