# Generated by Django 6.0.4 on 2026-05-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_warehousetransfer_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_returns',
            field=models.BooleanField(default=False, verbose_name='مستودع مرتجعات / توالف'),
        ),
    ]
