# Generated by Django 6.0.4 on 2026-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_warehouse_is_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousetransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
