# Generated by Django 6.0.4 on 2026-05-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_warehousetransfer_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemledger',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='loadingorderline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_order_lines', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockvoucherline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_voucher_lines', to='inventory.item'),
        ),
        migrations.AddConstraint(
            model_name='itemledger',
            constraint=models.UniqueConstraint(fields=('item', 'warehouse'), name='unique_item_warehouse'),
        ),
    ]
