# Generated by Django 5.1 on 2026-05-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_itemledger_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loadingorderline',
            constraint=models.UniqueConstraint(fields=('loading_order', 'item'), name='unique_loading_item'),
        ),
        migrations.AddConstraint(
            model_name='stockvoucherline',
            constraint=models.UniqueConstraint(fields=('voucher', 'item'), name='unique_voucher_item'),
        ),
        migrations.AddConstraint(
            model_name='warehousetransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'item'), name='unique_transfer_item'),
        ),
    ]
