# Generated by Django 5.1 on 2026-06-01 09:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_loadingorderline_unique_loading_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingorderline',
            name='approved_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loadingorderline',
            name='issued_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='loadingorderline',
            name='requested_qty',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='stockvoucherline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='stockvoucherline',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='stockvoucherline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سيتم حسابه تلقائياً عند الترحيل إذا كان إذن صرف', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='warehousetransferline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='warehousetransferline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='تكلفة الوحدة'),
        ),
    ]
