# Generated by Django 6.0.4 on 2026-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_add_model_validators_and_clean_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
