# Generated by Django 5.1 on 2026-06-02 18:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_stockmovement_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingorderline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الكمية الأساسية'),
        ),
        migrations.AddField(
            model_name='loadingorderline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='stockvoucherline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الكمية الأساسية'),
        ),
        migrations.AddField(
            model_name='stockvoucherline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='warehousetransferline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الكمية الأساسية'),
        ),
        migrations.AddField(
            model_name='warehousetransferline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
    ]
