# Generated by Django 6.0.4 on 2026-05-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='المسمى الوظيفي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف الوظيفي')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الإدارة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='hr.department', verbose_name='الإدارة الرئيسية')),
            ],
            options={
                'verbose_name': 'إدارة',
                'verbose_name_plural': 'الإدارات',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم القومي / الإقامة')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('hiring_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('contract_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد محدد المدة'), ('probation', 'فترة اختبار')], default='full_time', max_length=20, verbose_name='نوع العقد')),
                ('status', models.CharField(choices=[('active', 'على رأس العمل'), ('on_leave', 'في إجازة'), ('suspended', 'موقوف'), ('terminated', 'منهى خدمته')], default='active', max_length=20, verbose_name='الحالة')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب البنكي (IBAN)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department', verbose_name='الإدارة')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee', verbose_name='المدير المباشر')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.jobtitle', verbose_name='المسمى الوظيفي')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee', verbose_name='مدير الإدارة'),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'بطاقة رقم قومي / هوية'), ('passport', 'جواز سفر'), ('contract', 'عقد العمل'), ('criminal_record', 'فيش وتشبيه'), ('medical', 'شهادة طبية'), ('certificate', 'شهادة تخرج / خبرة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستند')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='hr/documents/', verbose_name='ملف المستند')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تمت المراجعة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
            ],
            options={
                'verbose_name': 'مستند الموظف',
                'verbose_name_plural': 'مستندات الموظفين',
            },
        ),
    ]
