# Generated by Django 6.0.4 on 2026-05-03 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_taxtype_category'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الإجازة')),
                ('days_allowed', models.PositiveIntegerField(default=21, verbose_name='الرصيد السنوي (أيام)')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة الأجر')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='تتطلب موافقة')),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوردية')),
                ('start_time', models.TimeField(verbose_name='وقت الحضور')),
                ('end_time', models.TimeField(verbose_name='وقت الانصراف')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, verbose_name='فترة السماح (دقائق)')),
            ],
            options={
                'verbose_name': 'وردية عمل',
                'verbose_name_plural': 'ورديات العمل',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100, verbose_name='اسم العهدة')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('delivery_date', models.DateField(verbose_name='تاريخ التسليم')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('is_returned', models.BooleanField(default=False, verbose_name='تم الرد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات وحالة العهدة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'عهدة عينية',
                'verbose_name_plural': 'العهد العينية',
            },
        ),
        migrations.CreateModel(
            name='EndOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField(verbose_name='تاريخ إنهاء الخدمة')),
                ('reason', models.CharField(max_length=100, verbose_name='سبب الإنهاء (استقالة، إقالة، تقاعد...)')),
                ('assets_returned', models.BooleanField(default=False, verbose_name='تم رد العهد العينية')),
                ('loans_settled', models.BooleanField(default=False, verbose_name='تم تسوية السلف')),
                ('severance_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مكافأة نهاية الخدمة')),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل رصيد إجازات')),
                ('total_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي التسوية النهائية')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت التسوية والمخالصة')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eos_record', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'نهاية خدمة',
                'verbose_name_plural': 'نهاية الخدمة',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الأيام')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('applied_on', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('manager_notes', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة/الرفض بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ السلفة')),
                ('installments_count', models.PositiveIntegerField(verbose_name='عدد شهور السداد')),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القسط الشهري')),
                ('start_month', models.DateField(verbose_name='تاريخ بداية الخصم')),
                ('reason', models.TextField(blank=True, verbose_name='سبب السلفة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('paid', 'مسددة بالكامل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفترة (مثال: راتب مايو 2026)')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الفترة')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية الفترة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('posted', 'مرحل (محاسبياً)')], default='draft', max_length=20, verbose_name='الحالة')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد الرواتب')),
            ],
            options={
                'verbose_name': 'فترة رواتب',
                'verbose_name_plural': 'فترات الرواتب',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور الفعلي')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف الفعلي')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('early_leave', 'انصراف مبكر'), ('on_leave', 'إجازة')], default='present', max_length=20, verbose_name='الحالة')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات العمل الإضافي')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل حضور وانصراف',
                'verbose_name_plural': 'سجلات الحضور والانصراف',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='إجمالي الرصيد')),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الأيام المستهلكة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'رصيد إجازات',
                'verbose_name_plural': 'أرصدة الإجازات',
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي البدلات')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الاستقطاعات (بما فيها السلف)')),
                ('social_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تأمينات اجتماعية (حصة الموظف)')),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ضريبة كسب العمل')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الراتب')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employee', verbose_name='الموظف')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollperiod', verbose_name='فترة الراتب')),
            ],
            options={
                'verbose_name': 'قسيمة راتب',
                'verbose_name_plural': 'قسائم الرواتب',
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
