# Generated by Django 6.0.4 on 2026-05-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leavetype_shift_employeeasset_endofservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_social_insurance',
            field=models.BooleanField(default=True, verbose_name='خاضع للتأمينات الاجتماعية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_taxes',
            field=models.BooleanField(default=True, verbose_name='خاضع لضريبة كسب العمل'),
        ),
    ]
