# Generated by Django 6.0.4 on 2026-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_has_social_insurance_employee_has_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='other_additions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إضافات أخرى (مكافآت، إلخ)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='استقطاعات أخرى (جزاءات، غياب)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدلات ثابتة'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم سلف'),
        ),
    ]
