# Generated by Django 6.0.4 on 2026-05-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_costcenter_options_costcenter_center_type_and_more'),
        ('hr', '0004_payslip_other_additions_payslip_other_deductions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.costcenter', verbose_name='مركز التكلفة المرتبط'),
        ),
    ]
