# Generated by Django 6.0.4 on 2026-05-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_department_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='income_tax_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='النسبة الفعلية للضريبة. في حال تطبيق الشرائح يتم تعديلها يدوياً في قسيمة الراتب.', max_digits=5, verbose_name='نسبة ضريبة كسب العمل (%)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_insurance_rate',
            field=models.DecimalField(decimal_places=2, default=11.0, help_text='مثال: 11 تعني 11% — تختلف حسب نوع التأمين (أجر متغير / ثابت / أصحاب أعمال)', max_digits=5, verbose_name='نسبة التأمينات (حصة الموظف %)'),
        ),
    ]
