# Generated by Django 6.0.4 on 2026-05-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_income_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف المهام والمسؤوليات'),
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('production', 'إنتاج وعمليات'), ('service', 'خدمات وفني'), ('marketing', 'تسويق ومبيعات'), ('admin', 'إداري ومالي'), ('hr', 'موارد بشرية'), ('it', 'تكنولوجيا معلومات'), ('rd', 'بحث وتطوير'), ('legal', 'شؤون قانونية'), ('procurement', 'مشتريات ولوجستيات'), ('projects', 'إدارة مشاريع'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع القسم/الإدارة'),
        ),
    ]
