# Generated by Django 6.0.4 on 2026-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_department_description_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('production', 'إنتاج وعمليات'), ('service', 'خدمات وفني'), ('marketing', 'تسويق ومبيعات'), ('admin', 'إداري ومالي'), ('hr', 'موارد بشرية'), ('it', 'تكنولوجيا معلومات'), ('rd', 'بحث وتطوير'), ('legal', 'شؤون قانونية'), ('procurement', 'مشتريات ولوجستيات'), ('projects', 'إدارة مشاريع'), ('technical', 'المكتب الفني'), ('pr', 'العلاقات العامة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع القسم/الإدارة'),
        ),
    ]
