# Generated by Django 6.0.4 on 2026-05-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_payslip_note_alter_department_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البند')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('item_type', models.CharField(choices=[('addition', 'إضافة (استحقاق)'), ('deduction', 'خصم (استقطاع)')], max_length=10, verbose_name='نوع البند')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.payslip', verbose_name='قسيمة الراتب')),
            ],
            options={
                'verbose_name': 'بند قسيمة راتب',
                'verbose_name_plural': 'بنود قسائم الرواتب',
            },
        ),
    ]
