# Generated by Django 6.0.4 on 2026-05-07 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_payslipitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المخصوم')),
                ('month', models.DateField(verbose_name='شهر القسط')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='hr.loan', verbose_name='السلفة')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_installments', to='hr.payslip', verbose_name='قسيمة الراتب')),
            ],
            options={
                'verbose_name': 'قسط سلفة',
                'verbose_name_plural': 'أقساط السلف',
                'unique_together': {('loan', 'payslip')},
            },
        ),
    ]
