# Generated by Django 6.0.4 on 2026-05-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journalentry_posted_at_journalentry_posted_by_and_more'),
        ('hr', '0010_loaninstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='gov_payment_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_gov_payment', to='core.journalentry', verbose_name='قيد توريد الاستقطاعات'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='insurance_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_insurance', to='core.journalentry', verbose_name='قيد حصة المنشأة'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='payment_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payment', to='core.journalentry', verbose_name='قيد صرف الرواتب'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accrual', to='core.journalentry', verbose_name='قيد الاستحقاق'),
        ),
    ]
