# Generated by Django 6.0.4 on 2026-05-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_payrollperiod_gov_payment_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='hr.department', verbose_name='الإدارة المرتبطة'),
        ),
    ]
