# Generated by Django 5.1 on 2026-05-31 16:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_jobtitle_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ساعات العمل الإضافي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='income_tax_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='النسبة الفعلية للضريبة. في حال تطبيق الشرائح يتم تعديلها يدوياً في قسيمة الراتب.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة ضريبة كسب العمل (%)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_insurance_rate',
            field=models.DecimalField(decimal_places=2, default=11.0, help_text='مثال: 11 تعني 11% — تختلف حسب نوع التأمين (أجر متغير / ثابت / أصحاب أعمال)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة التأمينات (حصة الموظف %)'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي الرصيد'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الأيام المستهلكة'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ السلفة'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='القسط الشهري'),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المخصوم'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ضريبة كسب العمل'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='صافي الراتب'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='other_additions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إضافات أخرى (مكافآت، إلخ)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='استقطاعات أخرى (جزاءات، غياب)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='social_insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تأمينات اجتماعية (حصة الموظف)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بدلات ثابتة'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='خصم سلف'),
        ),
        migrations.AlterField(
            model_name='payslipitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ'),
        ),
    ]
