# Generated by Django 6.0.4 on 2026-05-06 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_costcenter_options_costcenter_center_type_and_more'),
        ('treasury', '0002_banktransaction_bankreconciliation_cashtransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashtransfer',
            name='journal_entry',
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='issue_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_issue', to='core.journalentry'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='receive_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_receive', to='core.journalentry'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد التحويل (صادر)'), ('completed', 'مكتمل (مستلم)'), ('cancelled', 'ملغي')], default='draft', max_length=20),
        ),
    ]
