# Generated by Django 6.0.4 on 2026-05-07 12:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_remove_cashtransfer_journal_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
