# Generated by Django 6.0.4 on 2026-05-16 10:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_account_updated_at_account_version_and_more'),
        ('treasury', '0005_remove_bankreconciliation_is_reconciled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='رقم الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=200, verbose_name='اسم البنك'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='EGP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الحساب (داخلي)'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='book_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الرصيد في الدفاتر'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='difference',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الفارق'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='statement_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الرصيد في الكشف'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='statement_date',
            field=models.DateField(verbose_name='تاريخ كشف الحساب'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('completed', 'مكتملة (مطابقة)')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='treasury.banktransaction', verbose_name='العمليات المتضمنة'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateField(verbose_name='تاريخ العملية'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='description',
            field=models.TextField(verbose_name='الوصف/البيان'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='is_reconciled',
            field=models.BooleanField(default=False, verbose_name='تمت التسوية'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم العملية'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسوية'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='المرجع (رقم الحركة)'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('charge', 'عمولة بنكية'), ('interest', 'فائدة')], max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود الخزينة'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='currency',
            field=models.CharField(default='EGP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الخزينة'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='responsible_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عنها'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='date',
            field=models.DateField(verbose_name='تاريخ التحويل'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='from_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='treasury.bankaccount', verbose_name='من بنك'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='from_cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='treasury.cashbox', verbose_name='من خزينة'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='issue_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_issue', to='core.journalentry', verbose_name='قيد الصرف'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='receive_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_receive', to='core.journalentry', verbose_name='قيد الاستلام'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد التحويل (صادر)'), ('completed', 'مكتمل (مستلم)'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='to_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='treasury.bankaccount', verbose_name='إلى بنك'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='to_cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='treasury.cashbox', verbose_name='إلى خزينة'),
        ),
    ]
