# Generated by Django 6.0.4 on 2026-05-18 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemnotification'),
        ('treasury', '0006_alter_bankaccount_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المحفظة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المحفظة (الداخلي)')),
                ('provider', models.CharField(max_length=100, verbose_name='مزود الخدمة (مثال: فودافون كاش، إنستاباي)')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='رقم الهاتف المرتبط')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب المحاسبي')),
            ],
            options={
                'verbose_name': 'محفظة إلكترونية',
                'verbose_name_plural': 'المحافظ الإلكترونية',
            },
        ),
    ]
