# Generated by Django 6.0.4 on 2026-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_mobilewallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilewallet',
            name='provider',
            field=models.CharField(choices=[('vodafone', 'فودافون كاش (Vodafone Cash)'), ('instapay', 'إنستاباي (InstaPay)'), ('fawry', 'فوري (Fawry)'), ('orange', 'أورنج كاش (Orange Cash)'), ('etisalat', 'اتصالات كاش (Etisalat Cash)'), ('wepay', 'وي كاش (WE Pay)'), ('other', 'أخرى / محفظة بنكية')], default='vodafone', max_length=100, verbose_name='مزود الخدمة'),
        ),
    ]
