# Generated by Django 6.0.4 on 2026-05-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0008_alter_mobilewallet_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['bank_name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='bankreconciliation',
            options={'ordering': ['-statement_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='cashtransfer',
            options={'ordering': ['-date', '-id']},
        ),
    ]
