# Generated by Django 5.1 on 2026-05-31 16:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0009_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreconciliation',
            name='book_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الرصيد في الدفاتر'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='statement_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الرصيد في الكشف'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ'),
        ),
    ]
