# Generated by Django 6.0.4 on 2026-06-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0010_alter_bankreconciliation_book_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreconciliation',
            name='book_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الرصيد في الدفاتر'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='statement_balance',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الرصيد في الكشف'),
        ),
    ]
