# Generated by Django 5.1 on 2026-06-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_add_model_validators_and_clean_methods'),
        ('treasury', '0011_alter_bankreconciliation_book_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransfer',
            name='from_intermediary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='sales.intermediarycompany', verbose_name='من شركة وسيطة'),
        ),
    ]
