# Generated by Django 5.1 on 2026-06-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0012_cashtransfer_from_intermediary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('charge', 'عمولة بنكية'), ('interest', 'فائدة')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
