# Generated by Django 5.1 on 2026-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0013_alter_banktransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('account_fee', 'رسوم إدارة الحساب'), ('transfer_fee', 'عمولات التحويل البنكي'), ('bounce_fee', 'رسوم الشيكات المرتجعة'), ('stop_cheque_fee', 'رسوم إيقاف الشيكات'), ('chequebook_fee', 'مصروفات دفاتر الشيكات'), ('card_fee', 'عمولات بطاقات الائتمان/السحب'), ('loan_interest', 'فوائد قروض بنكية (مدينة)'), ('interest_rev', 'فوائد بنكية (دائنة)'), ('exchange_gain', 'أرباح فروق عملة'), ('exchange_loss', 'خسائر فروق عملة')], max_length=20, verbose_name='نوع العملية'),
        ),
    ]
