# Generated by Django 6.0.4 on 2026-05-06 08:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_journalentry_posted_at_journalentry_posted_by_and_more'),
        ('hr', '0009_payslipitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف التصنيف')),
                ('default_depreciation_rate', models.DecimalField(decimal_places=2, help_text='النسبة المئوية السنوية (مثال: 10.00)', max_digits=5, verbose_name='نسبة الإهلاك السنوية')),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acc_dep_categories', to='core.account', verbose_name='حساب مجمع الإهلاك')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='core.account', verbose_name='حساب الأصل')),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep_exp_categories', to='core.account', verbose_name='حساب مصروف الإهلاك')),
            ],
            options={
                'verbose_name': 'تصنيف أصول',
                'verbose_name_plural': 'تصنيفات الأصول',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الأصل')),
                ('name', models.CharField(max_length=300, verbose_name='اسم الأصل')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قيمة الشراء')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='القيمة التخريدية (الخردة)')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الإهلاك السنوية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('disposed', 'مستبعد'), ('fully_depreciated', 'مهلك بالكامل')], default='active', max_length=20, verbose_name='الحالة')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='الإدارة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
            },
        ),
        migrations.CreateModel(
            name='DepreciationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الإهلاك')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='مبلغ الإهلاك')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_logs', to='assets.asset')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'verbose_name': 'سجل إهلاك',
                'verbose_name_plural': 'سجلات الإهلاك',
                'ordering': ['-date'],
            },
        ),
    ]
