# Generated by Django 6.0.4 on 2026-05-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, help_text='النسبة المئوية التي يتم استقطاعها سنوياً (مثلاً: 10 للسيارات)', max_digits=5, verbose_name='نسبة الإهلاك السنوية'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='القيمة المتوقعة للأصل في نهاية عمره (كم سيساوي كخردة؟)', max_digits=18, verbose_name='القيمة التخريدية (الخردة)'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_depreciation_rate',
            field=models.DecimalField(decimal_places=2, help_text='النسبة الافتراضية لهذا النوع (مثلاً: 25% للحواسب، 10% للأثاث)', max_digits=5, verbose_name='نسبة الإهلاك السنوية'),
        ),
    ]
