# Generated by Django 6.0.4 on 2026-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_depreciation_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='initial_accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='إجمالي الإهلاك المتراكم للأصل قبل البدء في استخدام هذا النظام', max_digits=18, verbose_name='مجمع الإهلاك الافتتاحي'),
        ),
    ]
