# Generated by Django 5.1 on 2026-06-01 10:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_initial_accumulated_depreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, help_text='النسبة المئوية التي يتم استقطاعها سنوياً (مثلاً: 10 للسيارات)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الإهلاك السنوية'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='initial_accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='إجمالي الإهلاك المتراكم للأصل قبل البدء في استخدام هذا النظام', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مجمع الإهلاك الافتتاحي'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='القيمة المتوقعة للأصل في نهاية عمره (كم سيساوي كخردة؟)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='القيمة التخريدية (الخردة)'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_depreciation_rate',
            field=models.DecimalField(decimal_places=2, help_text='النسبة الافتراضية لهذا النوع (مثلاً: 25% للحواسب، 10% للأثاث)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الإهلاك السنوية'),
        ),
        migrations.AlterField(
            model_name='depreciationlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مبلغ الإهلاك'),
        ),
    ]
