# Generated by Django 5.1 on 2026-04-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('purchases', '0001_initial'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='invoices',
            field=models.ManyToManyField(through='purchases.PaymentAllocation', to='purchases.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplierpayment'),
        ),
    ]
