# Generated by Django 6.0.4 on 2026-04-25 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_journalline_account'),
        ('purchases', '0007_purchaseinvoiceline_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcenter'),
        ),
    ]
