# Generated by Django 6.0.4 on 2026-05-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fiscalyear_fy_dates_valid'),
        ('purchases', '0009_purchaseinvoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype'),
        ),
    ]
