# Generated by Django 6.0.4 on 2026-05-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_loadingorder_journal_entry'),
        ('purchases', '0010_purchaseinvoiceline_tax_percent2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure'),
        ),
    ]
