# Generated by Django 6.0.4 on 2026-05-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journalentry_posted_at_journalentry_posted_by_and_more'),
        ('purchases', '0011_purchaseinvoiceline_base_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcenter'),
        ),
    ]
