# Generated by Django 6.0.4 on 2026-05-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_purchasereturn_cost_center'),
        ('treasury', '0004_alter_cashtransfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='credit', max_length=10),
        ),
    ]
