# Generated by Django 6.0.4 on 2026-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_purchaseinvoice_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
