# Generated by Django 6.0.4 on 2026-05-16 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_supplierpayment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
    ]
