# Generated by Django 6.0.4 on 2026-05-16 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_account_updated_at_account_version_and_more'),
        ('inventory', '0014_remove_warehousetransfer_item_and_more'),
        ('purchases', '0015_purchaseinvoice_created_at_and_more'),
        ('treasury', '0006_alter_bankaccount_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ المخصص'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplierpayment', verbose_name='السند'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='due_date',
            field=models.DateField(verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='credit', max_length=10, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseorder', verbose_name='أمر الشراء المرتبط'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(max_length=100, verbose_name='رقم فاتورة المورد'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة 1'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة 2'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taxtype', verbose_name='نوع الضريبة 1'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype', verbose_name='نوع الضريبة 2'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام المتوقع'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم أمر الشراء'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('received', 'مستلم'), ('invoiced', 'مفوتر'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='date',
            field=models.DateField(verbose_name='تاريخ المرتجع'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم المرتجع'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم %'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasereturn', verbose_name='سند المرتجع'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة 1'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة 2'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.taxtype', verbose_name='نوع الضريبة 1'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.taxtype', verbose_name='نوع الضريبة 2'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.IntegerField(default=30, verbose_name='فترة السداد (أيام)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='date',
            field=models.DateField(verbose_name='تاريخ السداد'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='invoices',
            field=models.ManyToManyField(through='purchases.PaymentAllocation', to='purchases.purchaseinvoice', verbose_name='الفواتير المسددة'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم السند'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك'), ('cheque', 'شيك')], max_length=20, verbose_name='طريقة السداد'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='المرجع'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='المورد'),
        ),
    ]
