# Generated by Django 6.0.4 on 2026-05-24 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_alter_paymentallocation_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'verbose_name': 'توزيع سداد', 'verbose_name_plural': 'توزيعات السداد'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'فاتورة مشتريات', 'verbose_name_plural': 'فواتير المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoiceline',
            options={'verbose_name': 'صنف في فاتورة مشتريات', 'verbose_name_plural': 'أصناف فواتير المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'أمر شراء', 'verbose_name_plural': 'أوامر الشراء'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'مرتجع مشتريات', 'verbose_name_plural': 'مرتجعات المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturnline',
            options={'verbose_name': 'صنف في مرتجع مشتريات', 'verbose_name_plural': 'أصناف مرتجعات المشتريات'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['code'], 'verbose_name': 'مورد', 'verbose_name_plural': 'الموردون'},
        ),
        migrations.AlterModelOptions(
            name='supplierpayment',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'سند صرف مورد', 'verbose_name_plural': 'سندات صرف الموردين'},
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(db_index=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('received', 'مستلم'), ('invoiced', 'مفوتر'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ المرتجع'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم المورد'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ السداد'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'invoice')},
        ),
    ]
