# Generated by Django 6.0.4 on 2026-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0017_alter_paymentallocation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استحقاق الشيك'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الشيك'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cleared_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف الفعلي'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='is_cleared',
            field=models.BooleanField(default=False, verbose_name='تم الصرف الفعلي'),
        ),
    ]
