# Generated by Django 6.0.4 on 2026-05-28 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_supplierpayment_cheque_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentallocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
    ]
