# Generated by Django 6.0.4 on 2026-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_paymentallocation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم فاتورة المورد'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice'),
        ),
    ]
