# Generated by Django 5.1 on 2026-05-31 16:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_alter_paymentallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم %'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة ضريبة 1'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة ضريبة 2'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية بالوحدة الأساسية', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم %'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة ضريبة 1'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة ضريبة 2'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة'),
        ),
    ]
