# Generated by Django 6.0.4 on 2026-06-01 20:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0021_alter_purchaseinvoiceline_base_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المخصص'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الخصم'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الصافي'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='فترة السداد (أيام)'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ'),
        ),
    ]
