# Generated by Django 5.1 on 2026-06-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0022_alter_paymentallocation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='credit', max_length=10, verbose_name='طريقة السداد المعتادة'),
        ),
    ]
