# Generated by Django 5.1 on 2026-06-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0023_supplier_commercial_register_supplier_is_active_and_more'),
        ('treasury', '0011_alter_bankreconciliation_book_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة (للنقدي)'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='credit', max_length=10, verbose_name='نوع السداد'),
        ),
    ]
