# Generated by Django 6.0.4 on 2026-04-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_cost_center'),
        ('treasury', '0002_banktransaction_bankreconciliation_cashtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodysettlement',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='expenses_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
