# Generated by Django 6.0.4 on 2026-05-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_subtotal_expense_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('posted', 'مرحّل'), ('reversed', 'معكوس'), ('rejected', 'مرفوض')], default='draft', max_length=20),
        ),
    ]
