# Generated by Django 6.0.4 on 2026-05-16 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_account_updated_at_account_version_and_more'),
        ('expenses', '0008_custody_created_at_custody_updated_at_and_more'),
        ('treasury', '0006_alter_bankaccount_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='custody',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='حساب ذمة الموظف'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='قيمة العهدة'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='cash_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة الصادر منها'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='date',
            field=models.DateField(verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المستلم'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم العهدة'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='purpose',
            field=models.TextField(verbose_name='الغرض من العهدة'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ المسوي'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('partial', 'مسواة جزئياً'), ('settled', 'مسواة')], default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة المودع بها'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='custody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='expenses.custody', verbose_name='العهدة الأصلية'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='date',
            field=models.DateField(verbose_name='تاريخ التسوية'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='expenses_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي المصاريف (فواتير)'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='تم الترحيل'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ المتبقي (المرتجع)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ المدفوع فعلياً (الصافي)', max_digits=18, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, upload_to='expenses/', verbose_name='المرفقات (صورة الفاتورة)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='الخزينة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.expensecategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='custody',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.custody', verbose_name='العهدة المرتبطة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(verbose_name='البيان/الوصف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم المصروف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك'), ('custody', 'عهدة')], max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.custodysettlement', verbose_name='تسوية العهدة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('posted', 'مرحّل'), ('reversed', 'معكوس'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='المبلغ قبل الضريبة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة 1'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة ضريبة 2'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses1', to='core.taxtype', verbose_name='نوع الضريبة 1'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses2', to='core.taxtype', verbose_name='نوع الضريبة 2'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم التصنيف'),
        ),
    ]
