# Generated by Django 6.0.4 on 2026-05-24 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_custody_account_alter_custody_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custody',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'عهدة', 'verbose_name_plural': 'العهد'},
        ),
        migrations.AlterModelOptions(
            name='custodysettlement',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'تسوية عهدة', 'verbose_name_plural': 'تسويات العهد'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['name'], 'verbose_name': 'تصنيف مصروف', 'verbose_name_plural': 'تصنيفات المصروفات'},
        ),
        migrations.AddField(
            model_name='custody',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_custodies', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='custodysettlement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('partial', 'مسواة جزئياً'), ('settled', 'مسواة')], db_index=True, default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='is_posted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تم الترحيل'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الصرف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('posted', 'مرحّل'), ('reversed', 'معكوس'), ('rejected', 'مرفوض')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
