# Generated by Django 6.0.4 on 2026-05-27 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_custody_options_and_more'),
        ('hr', '0012_jobtitle_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custody',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='الموظف المستلم'),
        ),
    ]
