# Generated by Django 5.1 on 2026-05-31 16:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_custody_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custody',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قيمة العهدة'),
        ),
        migrations.AlterField(
            model_name='custody',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المسوي'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='expenses_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي المصاريف (فواتير)'),
        ),
        migrations.AlterField(
            model_name='custodysettlement',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المتبقي (المرتجع)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='المبلغ المدفوع فعلياً (الصافي)', max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ قبل الضريبة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='إجمالي الضريبة'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة ضريبة 1'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tax_percent2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة ضريبة 2'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الإجمالي'),
        ),
    ]
