# Generated by Django 6.0.4 on 2026-05-17 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0015_warehouse_is_returns'),
        ('sales', '0025_alter_customer_account_alter_customer_address_and_more'),
        ('treasury', '0006_alter_bankaccount_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإيصال')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الإجمالي قبل الضريبة والخصم')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الخصم')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الضريبة')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='الصافي المطلوب')),
                ('status', models.CharField(choices=[('draft', 'مسودة (قيد الإدخال)'), ('paid', 'مدفوعة (جاهزة للتسليم)'), ('posted', 'مرحّلة للـ ERP (كفاتورة مبيعات)'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='العميل (يُترك فارغاً للعميل النقدي)')),
                ('sales_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice', verbose_name='فاتورة المبيعات الضريبية المرتبطة')),
            ],
            options={
                'verbose_name': 'طلب نقطة بيع',
                'verbose_name_plural': 'طلبات نقاط البيع',
            },
        ),
        migrations.CreateModel(
            name='POSOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='خصم السطر')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='إجمالي السطر')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='الصنف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.posorder')),
            ],
            options={
                'verbose_name': 'سطر طلب نقطة بيع',
                'verbose_name_plural': 'أسطر طلبات نقاط البيع',
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'كاش (نقدية)'), ('card', 'بطاقة بنكية (فيزا/ماستركارد)'), ('wallet', 'محفظة إلكترونية / فوري')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='المبلغ المدفوع')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='رقم العملية (للفيزا/المحفظة)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.posorder')),
            ],
            options={
                'verbose_name': 'مدفوعات نقطة بيع',
                'verbose_name_plural': 'مدفوعات نقاط البيع',
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت فتح الوردية')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت إغلاق الوردية')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='عُهدة الفتح (الكاش المبدئي)')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='النقدية المتوقعة بنهاية الوردية')),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='النقدية الفعلية (الجرد الفعلي)')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='العجز / الزيادة')),
                ('status', models.CharField(choices=[('open', 'مفتوحة (قيد العمل)'), ('closed', 'مغلقة'), ('posted', 'مرحّلة (تمت التسوية)')], default='open', max_length=20, verbose_name='حالة الوردية')),
                ('settlement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.repdailysettlement', verbose_name='التسوية اليومية المرتبطة بالـ ERP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='الكاشير (المستخدم)')),
            ],
            options={
                'verbose_name': 'وردية نقطة بيع',
                'verbose_name_plural': 'ورديات نقاط البيع',
            },
        ),
        migrations.AddField(
            model_name='posorder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pos.possession', verbose_name='الوردية'),
        ),
        migrations.CreateModel(
            name='POSStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود النقطة')),
                ('name', models.CharField(max_length=100, verbose_name='اسم نقطة البيع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.bankaccount', verbose_name='حساب البنك (لمدفوعات الفيزا)')),
                ('cash_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.cashbox', verbose_name='درج النقدية (الخزينة الافتراضية)')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المخزن المرتبط (لسحب البضاعة)')),
            ],
            options={
                'verbose_name': 'نقطة بيع',
                'verbose_name_plural': 'نقاط البيع',
            },
        ),
        migrations.AddField(
            model_name='possession',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos.posstation', verbose_name='نقطة البيع'),
        ),
    ]
