# Generated by Django 6.0.4 on 2026-05-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('treasury', '0007_mobilewallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='posstation',
            name='mobile_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.mobilewallet', verbose_name='المحفظة الإلكترونية المرتبطة'),
        ),
    ]
