# Generated by Django 6.0.4 on 2026-05-24 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_posstation_mobile_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posorderline',
            options={'ordering': ['-id'], 'verbose_name': 'سطر طلب نقطة بيع', 'verbose_name_plural': 'أسطر طلبات نقاط البيع'},
        ),
        migrations.AlterModelOptions(
            name='pospayment',
            options={'ordering': ['-id'], 'verbose_name': 'مدفوعات نقطة بيع', 'verbose_name_plural': 'مدفوعات نقاط البيع'},
        ),
        migrations.AddField(
            model_name='posorderline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='posorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='posorderline',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='pospayment',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),
    ]
