# Generated by Django 6.0.4 on 2026-05-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_posorderline_options_alter_pospayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='shortage_collected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تم تحصيل العجز في'),
        ),
    ]
