# Generated by Django 6.0.4 on 2026-05-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_possession_shortage_collected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='pos.posorder'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.posorder'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم العملية (للفيزا/المحفظة)'),
        ),
    ]
