# Generated by Django 5.1 on 2026-06-01 10:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_posorderline_order_alter_pospayment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الصافي المطلوب'),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الإجمالي قبل الضريبة والخصم'),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='الضريبة'),
        ),
        migrations.AlterField(
            model_name='posorderline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='خصم السطر'),
        ),
        migrations.AlterField(
            model_name='posorderline',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='posorderline',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='posorderline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='نسبة الضريبة'),
        ),
        migrations.AlterField(
            model_name='posorderline',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='إجمالي السطر'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='actual_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='النقدية الفعلية (الجرد الفعلي)'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='النقدية المتوقعة بنهاية الوردية'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='opening_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='عُهدة الفتح (الكاش المبدئي)'),
        ),
    ]
