# Generated by Django 5.1 on 2026-06-01 20:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_add_model_validators_and_clean_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pospayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المدفوع'),
        ),
    ]
