# Generated by Django 5.1 on 2026-06-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_pospayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='إيصال مرتجع'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='pos.posorder', verbose_name='الفاتورة الأصلية (للمرتجعات)'),
        ),
    ]
