# Generated by Django 6.0.4 on 2026-05-08 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company_name_ar', models.CharField(max_length=200, verbose_name='اسم الشركة (عربي)')),
                ('company_name_en', models.CharField(max_length=200, verbose_name='اسم الشركة (إنجليزي)')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(max_length=50, verbose_name='السجل التجاري')),
                ('VAT_number', models.CharField(max_length=50, verbose_name='الرقم المرجعي للضريبة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('branch_code', models.CharField(default='0', max_length=10, verbose_name='كود الفرع')),
                ('governorate', models.CharField(max_length=50, verbose_name='المحافظة')),
                ('region_city', models.CharField(max_length=50, verbose_name='المنطقة/المدينة')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('document_type_issue', models.CharField(choices=[('invoice', 'فاتورة'), ('credit_note', 'إشعار دائن'), ('debit_note', 'إشعار مدين')], default='invoice', max_length=20, verbose_name='نوع الوثيقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركات',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشهادة')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('certificate_file', models.FileField(upload_to='certificates/', verbose_name='ملف الشهادة (P12)')),
                ('password_encrypted', models.CharField(max_length=500, verbose_name='كلمة المرور (مشفرة)')),
                ('issued_to', models.CharField(max_length=200, verbose_name='صادرة لـ')),
                ('issued_by', models.CharField(max_length=200, verbose_name='جهة الإصدار')),
                ('valid_from', models.DateField(verbose_name='صالحة من')),
                ('valid_until', models.DateField(verbose_name='صالحة حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='e_invoice.companysettings', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'شهادة رقمية',
                'verbose_name_plural': 'الشهادات الرقمية',
            },
        ),
        migrations.CreateModel(
            name='EInvoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('production', 'إنتاج'), ('test', 'اختبار')], default='test', max_length=20, verbose_name='البيئة')),
                ('api_base_url', models.URLField(verbose_name='رابط API')),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=200, verbose_name='Client Secret')),
                ('security_token', models.CharField(blank=True, max_length=500, verbose_name='Security Token')),
                ('auto_submit', models.BooleanField(default=False, verbose_name='إرسال تلقائي عند الترحيل')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='مهلة الانتظار (ثواني)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='e_invoice_config', to='e_invoice.companysettings', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'إعدادات الفاتورة الإلكترونية',
                'verbose_name_plural': 'إعدادات الفاتورة الإلكترونية',
            },
        ),
        migrations.CreateModel(
            name='EInvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('internal_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم المرجعي الداخلي')),
                ('uuid', models.CharField(blank=True, max_length=100, verbose_name='UUID')),
                ('submission_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الإرسال')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسلة'), ('valid', 'صحيحة'), ('invalid', 'غير صحيحة'), ('cancelled', 'ملغاة'), ('cancelled_correct', 'ملغاة بتصحيح')], default='draft', max_length=30, verbose_name='الحالة')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('raw_request', models.JSONField(blank=True, null=True, verbose_name='الطلب الأصلي')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='الاستجابة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_invoice_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل الفاتورة الإلكترونية',
                'verbose_name_plural': 'سجلات الفاتورة الإلكترونية',
                'ordering': ['-created_at'],
            },
        ),
    ]
