# Generated by Django 6.0.4 on 2026-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoicelog',
            name='internal_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='الرقم المرجعي الداخلي'),
        ),
        migrations.AlterField(
            model_name='einvoicelog',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسلة'), ('valid', 'صحيحة'), ('invalid', 'غير صحيحة'), ('cancelled', 'ملغاة'), ('cancelled_correct', 'ملغاة بتصحيح')], db_index=True, default='draft', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='einvoicelog',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='UUID'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='unique_default_cert_per_company'),
        ),
    ]
