# Generated by Django 5.1 on 2026-06-01 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_invoice', '0002_alter_einvoicelog_internal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoiceconfig',
            name='timeout_seconds',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='مهلة الانتظار (ثواني)'),
        ),
    ]
